### PR TITLE
Added token info api and health api

### PR DESCRIPTION
**Pull request by Crypto-One-dev**

### CODE REVIEW

**Comment by Cryo45** [comment]
Looks good!
1. Can you also include the freshness of data in readable form. For example: `lastUpdated: "2 hours ago"`. We can use a library https://www.npmjs.com/package/timeago.js .
2. Let's add tests. Two success scenario tests that call `/health` and `tokens-info` and check some parts of the output would be good.

Thank you!

**Comment by Cryo45** [comment]
screen-245

screen-246

Since it is small and related, can we also drop the useless `uiData` from here and replace it with the "time ago" field and value?

**Comment by Crypto-One-dev** [comment]
Got it

**Comment by Cryo45** [comment]
The code looks good. i will merge it.
I suggest adding tests in another PR. There are existing tests already, you can just follow the examples.

**Pull request merged**
