### PR TITLE
moved to inactive category

### PR DESCRIPTION
**Pull request by Crypto-One-dev**

### CODE REVIEW

**Review by CryptJS13 — COMMENTED** [review]
Looks good! I am not 100% if this is gonna work as expected for the FARM_GRAIN_LP, as that is not technically a vault, but a rewardPool. Maybe @Cryo45 can advise on that.

**Comment by CryptJS13** [comment]
@Crypto-One-dev It seems you forgot the BELT-BNB vault on BSC.

**Comment by Crypto-One-dev** [comment]
Okay, I will fix soon

**Comment by Crypto-One-dev** [comment]
Well, I did it.
Please check this:
image

**Comment by CryptJS13** [comment]
> Well, I did it.
> Please check this:
> image
> 

I think that was inactive already. belt_BELT_BNB needs to be moved now

**Comment by Cryo45** [comment]
To make a special pool like `FARM/GRAIN` inactive, have to change it in `harvest-front` UI repo, by setting this flag: https://github.com/harvest-finance/harvest-front/blob/master/src/components/VaultList/index.js#L309, on the pool above the pool highlighted by the line. Let's remove the `FARM_GRAIN_LP` change from this PR.

**Comment by CryptJS13** [comment]
@Crypto-One-dev Still missing the one pool. It's called belt_BELT_BNB in `tokens`

**Comment by CryptJS13** [comment]
Alright, thanks! Good to merge

**Review by Cryo45 — APPROVED** [review]

**Pull request merged**
