### PR TITLE
removed wmatic from rewardTokens of polygon pools

### PR DESCRIPTION
**Pull request by Crypto-One-dev**

### CODE REVIEW

**Review by CryptJS13 — APPROVED** [review]
Looks good!

**Comment by Cryo45** [comment]
1. i believe we need to remove the token from `rewardTokens` too
2. let's look at the front-end repo to confirm that when `WMATIC` is in the middle: `[addresses.MATIC.miFARM, addresses.MATIC.WMATIC, addresses.MATIC.pGENE` and it is removed, that UI is not confused by the fact that reward tokens are not in the same order as in smart contract.

**Comment by CryptJS13** [comment]
> 1. i believe we need to remove the token from `rewardTokens` too
> 2. let's look at the front-end repo to confirm that when `WMATIC` is in the middle: `[addresses.MATIC.miFARM, addresses.MATIC.WMATIC, addresses.MATIC.pGENE` and it is removed, that UI is not confused by the fact that reward tokens are not in the same order as in smart contract.

I wanted to leave it in `rewardTokens` for now, so users can still see their wMATIC balance in the UI. We can remove it next week. This way (I believe), it will not show the icon with the other rewards, but it will show the wmatic balance in the vault card.

**Comment by Cryo45** [comment]
yes, i agree. Will merge now and observe!

**Pull request merged**
